version: '3'

includes:
  ui:
    taskfile: ./ui/Taskfile.yml
    dir: ./ui

tasks:
  default:
    cmds:
      - task: generate
      - task: build-driftd
      - task: build-driftctl
      - task: ui:build
  generate:
    run: when_changed
    cmds:
      - go generate .
      - go mod tidy
    sources:
      - ent/schema/*.go
      - ent/entc.go
      - gqlgen.yml
  build-driftd:
    run: when_changed
    deps: [generate]
    sources:
      - cmd/driftd/*.go
      - ent/*.go
      - ./*.go
    generates:
      - driftd
    cmds:
      - go build -o driftd cmd/driftd/*.go 
  build-driftctl:
    run: when_changed
    deps: [generate]
    sources:
      - cmd/driftctl/*.go
      - ent/*.go
      - ./*.go
    generates:
      - driftctl
    cmds:
      - go build -o driftctl cmd/driftctl/*.go 
  chart:
    run: when_changed
    sources:
      - chart/*.yaml
      - templates/*/*.yaml
    generates:
      - ./drift-0.1.0.tgz
    cmds:
      - helm package ./chart
  docker:
    cmds:
      - task: ui:docker
      - docker build -t drift/driftd -f Dockerfile.driftd .
  deploy:
    run: when_changed
    deps: [chart,push]
    sources:
      - ./drift-0.1.0.tgz
      - local.yaml
    cmds:
      - helm upgrade --install --create-namespace dev -n dev ./drift-0.1.0.tgz --values local.yaml
  push:
    cmds:
      - docker tag drift/driftd drift-registry.localhost:5000/drift/driftd
      - docker push drift-registry.localhost:5000/drift/driftd
      - docker tag drift/drift-ui drift-registry.localhost:5000/drift/drift-ui
      - docker push drift-registry.localhost:5000/drift/drift-ui
