version: '3'

includes:
  ui:
    taskfile: ./ui/Taskfile.yml
    dir: ./ui

tasks:
  default:
    cmds:
      - task: generate
      - task: build-driftd
      - task: build-driftctl
      - task: ui:build
  generate:
    run: when_changed
    cmds:
      - go generate .
      - go mod tidy
    sources:
      - ent/schema/*.go
      - ent/entc.go
      - gqlgen.yml
  build-driftd:
    run: when_changed
    deps: [generate]
    sources:
      - cmd/driftd/*.go
      - ent/*.go
      - ./*.go
    generates:
      - driftd
    cmds:
      - go build -o driftd cmd/driftd/*.go 
  build-driftctl:
    run: when_changed
    deps: [generate]
    sources:
      - cmd/driftctl/*.go
      - ent/*.go
      - ./*.go
    generates:
      - driftctl
    cmds:
      - go build -o driftctl cmd/driftctl/*.go 
