{{- if .Values.driftd.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: driftd-sa
  labels:
    app.kubernetes.io/name: driftd
    app.kubernetes.io/instance: drift
  {{- with .Values.driftd.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
