// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UttersColumns holds the columns for the "utters" table.
	UttersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "data", Type: field.TypeString},
		{Name: "user_utters", Type: field.TypeInt, Nullable: true},
	}
	// UttersTable holds the schema information for the "utters" table.
	UttersTable = &schema.Table{
		Name:       "utters",
		Columns:    UttersColumns,
		PrimaryKey: []*schema.Column{UttersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "utters_users_utters",
				Columns:    []*schema.Column{UttersColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		UttersTable,
	}
)

func init() {
	UttersTable.ForeignKeys[0].RefTable = UsersTable
}
