apiVersion: apps/v1
kind: Deployment
metadata:
  name: driftd
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: driftd
      app.kubernetes.io/instance: drift
  template:
    metadata:
      {{- with .Values.driftd.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: driftd
        app.kubernetes.io/instance: drift
    spec:
      {{- with .Values.driftd.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: driftd-sa
      securityContext:
        {{- toYaml .Values.driftd.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.driftd.securityContext | nindent 12 }}
          image: "{{ .Values.driftd.image.repository }}:{{ .Values.driftd.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.driftd.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.driftd.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.driftd.resources | nindent 12 }}
      {{- with .Values.driftd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.driftd.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.driftd.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
