// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nibbleshift/drift/ent/post"
	"github.com/nibbleshift/drift/ent/predicate"
	"github.com/nibbleshift/drift/ent/userprofile"
)

// UserProfileUpdate is the builder for updating UserProfile entities.
type UserProfileUpdate struct {
	config
	hooks    []Hook
	mutation *UserProfileMutation
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (upu *UserProfileUpdate) Where(ps ...predicate.UserProfile) *UserProfileUpdate {
	upu.mutation.Where(ps...)
	return upu
}

// SetAvatar sets the "avatar" field.
func (upu *UserProfileUpdate) SetAvatar(s string) *UserProfileUpdate {
	upu.mutation.SetAvatar(s)
	return upu
}

// SetAbout sets the "about" field.
func (upu *UserProfileUpdate) SetAbout(s string) *UserProfileUpdate {
	upu.mutation.SetAbout(s)
	return upu
}

// SetLocation sets the "location" field.
func (upu *UserProfileUpdate) SetLocation(s string) *UserProfileUpdate {
	upu.mutation.SetLocation(s)
	return upu
}

// SetDob sets the "dob" field.
func (upu *UserProfileUpdate) SetDob(t time.Time) *UserProfileUpdate {
	upu.mutation.SetDob(t)
	return upu
}

// AddLinkIDs adds the "links" edge to the Post entity by IDs.
func (upu *UserProfileUpdate) AddLinkIDs(ids ...int) *UserProfileUpdate {
	upu.mutation.AddLinkIDs(ids...)
	return upu
}

// AddLinks adds the "links" edges to the Post entity.
func (upu *UserProfileUpdate) AddLinks(p ...*Post) *UserProfileUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return upu.AddLinkIDs(ids...)
}

// AddEmailIDs adds the "emails" edge to the UserProfile entity by IDs.
func (upu *UserProfileUpdate) AddEmailIDs(ids ...int) *UserProfileUpdate {
	upu.mutation.AddEmailIDs(ids...)
	return upu
}

// AddEmails adds the "emails" edges to the UserProfile entity.
func (upu *UserProfileUpdate) AddEmails(u ...*UserProfile) *UserProfileUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return upu.AddEmailIDs(ids...)
}

// AddFollowerIDs adds the "followers" edge to the UserProfile entity by IDs.
func (upu *UserProfileUpdate) AddFollowerIDs(ids ...int) *UserProfileUpdate {
	upu.mutation.AddFollowerIDs(ids...)
	return upu
}

// AddFollowers adds the "followers" edges to the UserProfile entity.
func (upu *UserProfileUpdate) AddFollowers(u ...*UserProfile) *UserProfileUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return upu.AddFollowerIDs(ids...)
}

// Mutation returns the UserProfileMutation object of the builder.
func (upu *UserProfileUpdate) Mutation() *UserProfileMutation {
	return upu.mutation
}

// ClearLinks clears all "links" edges to the Post entity.
func (upu *UserProfileUpdate) ClearLinks() *UserProfileUpdate {
	upu.mutation.ClearLinks()
	return upu
}

// RemoveLinkIDs removes the "links" edge to Post entities by IDs.
func (upu *UserProfileUpdate) RemoveLinkIDs(ids ...int) *UserProfileUpdate {
	upu.mutation.RemoveLinkIDs(ids...)
	return upu
}

// RemoveLinks removes "links" edges to Post entities.
func (upu *UserProfileUpdate) RemoveLinks(p ...*Post) *UserProfileUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return upu.RemoveLinkIDs(ids...)
}

// ClearEmails clears all "emails" edges to the UserProfile entity.
func (upu *UserProfileUpdate) ClearEmails() *UserProfileUpdate {
	upu.mutation.ClearEmails()
	return upu
}

// RemoveEmailIDs removes the "emails" edge to UserProfile entities by IDs.
func (upu *UserProfileUpdate) RemoveEmailIDs(ids ...int) *UserProfileUpdate {
	upu.mutation.RemoveEmailIDs(ids...)
	return upu
}

// RemoveEmails removes "emails" edges to UserProfile entities.
func (upu *UserProfileUpdate) RemoveEmails(u ...*UserProfile) *UserProfileUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return upu.RemoveEmailIDs(ids...)
}

// ClearFollowers clears all "followers" edges to the UserProfile entity.
func (upu *UserProfileUpdate) ClearFollowers() *UserProfileUpdate {
	upu.mutation.ClearFollowers()
	return upu
}

// RemoveFollowerIDs removes the "followers" edge to UserProfile entities by IDs.
func (upu *UserProfileUpdate) RemoveFollowerIDs(ids ...int) *UserProfileUpdate {
	upu.mutation.RemoveFollowerIDs(ids...)
	return upu
}

// RemoveFollowers removes "followers" edges to UserProfile entities.
func (upu *UserProfileUpdate) RemoveFollowers(u ...*UserProfile) *UserProfileUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return upu.RemoveFollowerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (upu *UserProfileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, upu.sqlSave, upu.mutation, upu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (upu *UserProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := upu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (upu *UserProfileUpdate) Exec(ctx context.Context) error {
	_, err := upu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upu *UserProfileUpdate) ExecX(ctx context.Context) {
	if err := upu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (upu *UserProfileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userprofile.Table, userprofile.Columns, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt))
	if ps := upu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := upu.mutation.Avatar(); ok {
		_spec.SetField(userprofile.FieldAvatar, field.TypeString, value)
	}
	if value, ok := upu.mutation.About(); ok {
		_spec.SetField(userprofile.FieldAbout, field.TypeString, value)
	}
	if value, ok := upu.mutation.Location(); ok {
		_spec.SetField(userprofile.FieldLocation, field.TypeString, value)
	}
	if value, ok := upu.mutation.Dob(); ok {
		_spec.SetField(userprofile.FieldDob, field.TypeTime, value)
	}
	if upu.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.LinksTable,
			Columns: []string{userprofile.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upu.mutation.RemovedLinksIDs(); len(nodes) > 0 && !upu.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.LinksTable,
			Columns: []string{userprofile.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upu.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.LinksTable,
			Columns: []string{userprofile.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if upu.mutation.EmailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.EmailsTable,
			Columns: userprofile.EmailsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upu.mutation.RemovedEmailsIDs(); len(nodes) > 0 && !upu.mutation.EmailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.EmailsTable,
			Columns: userprofile.EmailsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upu.mutation.EmailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.EmailsTable,
			Columns: userprofile.EmailsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if upu.mutation.FollowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.FollowersTable,
			Columns: userprofile.FollowersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upu.mutation.RemovedFollowersIDs(); len(nodes) > 0 && !upu.mutation.FollowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.FollowersTable,
			Columns: userprofile.FollowersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upu.mutation.FollowersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.FollowersTable,
			Columns: userprofile.FollowersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, upu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	upu.mutation.done = true
	return n, nil
}

// UserProfileUpdateOne is the builder for updating a single UserProfile entity.
type UserProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserProfileMutation
}

// SetAvatar sets the "avatar" field.
func (upuo *UserProfileUpdateOne) SetAvatar(s string) *UserProfileUpdateOne {
	upuo.mutation.SetAvatar(s)
	return upuo
}

// SetAbout sets the "about" field.
func (upuo *UserProfileUpdateOne) SetAbout(s string) *UserProfileUpdateOne {
	upuo.mutation.SetAbout(s)
	return upuo
}

// SetLocation sets the "location" field.
func (upuo *UserProfileUpdateOne) SetLocation(s string) *UserProfileUpdateOne {
	upuo.mutation.SetLocation(s)
	return upuo
}

// SetDob sets the "dob" field.
func (upuo *UserProfileUpdateOne) SetDob(t time.Time) *UserProfileUpdateOne {
	upuo.mutation.SetDob(t)
	return upuo
}

// AddLinkIDs adds the "links" edge to the Post entity by IDs.
func (upuo *UserProfileUpdateOne) AddLinkIDs(ids ...int) *UserProfileUpdateOne {
	upuo.mutation.AddLinkIDs(ids...)
	return upuo
}

// AddLinks adds the "links" edges to the Post entity.
func (upuo *UserProfileUpdateOne) AddLinks(p ...*Post) *UserProfileUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return upuo.AddLinkIDs(ids...)
}

// AddEmailIDs adds the "emails" edge to the UserProfile entity by IDs.
func (upuo *UserProfileUpdateOne) AddEmailIDs(ids ...int) *UserProfileUpdateOne {
	upuo.mutation.AddEmailIDs(ids...)
	return upuo
}

// AddEmails adds the "emails" edges to the UserProfile entity.
func (upuo *UserProfileUpdateOne) AddEmails(u ...*UserProfile) *UserProfileUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return upuo.AddEmailIDs(ids...)
}

// AddFollowerIDs adds the "followers" edge to the UserProfile entity by IDs.
func (upuo *UserProfileUpdateOne) AddFollowerIDs(ids ...int) *UserProfileUpdateOne {
	upuo.mutation.AddFollowerIDs(ids...)
	return upuo
}

// AddFollowers adds the "followers" edges to the UserProfile entity.
func (upuo *UserProfileUpdateOne) AddFollowers(u ...*UserProfile) *UserProfileUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return upuo.AddFollowerIDs(ids...)
}

// Mutation returns the UserProfileMutation object of the builder.
func (upuo *UserProfileUpdateOne) Mutation() *UserProfileMutation {
	return upuo.mutation
}

// ClearLinks clears all "links" edges to the Post entity.
func (upuo *UserProfileUpdateOne) ClearLinks() *UserProfileUpdateOne {
	upuo.mutation.ClearLinks()
	return upuo
}

// RemoveLinkIDs removes the "links" edge to Post entities by IDs.
func (upuo *UserProfileUpdateOne) RemoveLinkIDs(ids ...int) *UserProfileUpdateOne {
	upuo.mutation.RemoveLinkIDs(ids...)
	return upuo
}

// RemoveLinks removes "links" edges to Post entities.
func (upuo *UserProfileUpdateOne) RemoveLinks(p ...*Post) *UserProfileUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return upuo.RemoveLinkIDs(ids...)
}

// ClearEmails clears all "emails" edges to the UserProfile entity.
func (upuo *UserProfileUpdateOne) ClearEmails() *UserProfileUpdateOne {
	upuo.mutation.ClearEmails()
	return upuo
}

// RemoveEmailIDs removes the "emails" edge to UserProfile entities by IDs.
func (upuo *UserProfileUpdateOne) RemoveEmailIDs(ids ...int) *UserProfileUpdateOne {
	upuo.mutation.RemoveEmailIDs(ids...)
	return upuo
}

// RemoveEmails removes "emails" edges to UserProfile entities.
func (upuo *UserProfileUpdateOne) RemoveEmails(u ...*UserProfile) *UserProfileUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return upuo.RemoveEmailIDs(ids...)
}

// ClearFollowers clears all "followers" edges to the UserProfile entity.
func (upuo *UserProfileUpdateOne) ClearFollowers() *UserProfileUpdateOne {
	upuo.mutation.ClearFollowers()
	return upuo
}

// RemoveFollowerIDs removes the "followers" edge to UserProfile entities by IDs.
func (upuo *UserProfileUpdateOne) RemoveFollowerIDs(ids ...int) *UserProfileUpdateOne {
	upuo.mutation.RemoveFollowerIDs(ids...)
	return upuo
}

// RemoveFollowers removes "followers" edges to UserProfile entities.
func (upuo *UserProfileUpdateOne) RemoveFollowers(u ...*UserProfile) *UserProfileUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return upuo.RemoveFollowerIDs(ids...)
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (upuo *UserProfileUpdateOne) Where(ps ...predicate.UserProfile) *UserProfileUpdateOne {
	upuo.mutation.Where(ps...)
	return upuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (upuo *UserProfileUpdateOne) Select(field string, fields ...string) *UserProfileUpdateOne {
	upuo.fields = append([]string{field}, fields...)
	return upuo
}

// Save executes the query and returns the updated UserProfile entity.
func (upuo *UserProfileUpdateOne) Save(ctx context.Context) (*UserProfile, error) {
	return withHooks(ctx, upuo.sqlSave, upuo.mutation, upuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (upuo *UserProfileUpdateOne) SaveX(ctx context.Context) *UserProfile {
	node, err := upuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (upuo *UserProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := upuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upuo *UserProfileUpdateOne) ExecX(ctx context.Context) {
	if err := upuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (upuo *UserProfileUpdateOne) sqlSave(ctx context.Context) (_node *UserProfile, err error) {
	_spec := sqlgraph.NewUpdateSpec(userprofile.Table, userprofile.Columns, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt))
	id, ok := upuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := upuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userprofile.FieldID)
		for _, f := range fields {
			if !userprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := upuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := upuo.mutation.Avatar(); ok {
		_spec.SetField(userprofile.FieldAvatar, field.TypeString, value)
	}
	if value, ok := upuo.mutation.About(); ok {
		_spec.SetField(userprofile.FieldAbout, field.TypeString, value)
	}
	if value, ok := upuo.mutation.Location(); ok {
		_spec.SetField(userprofile.FieldLocation, field.TypeString, value)
	}
	if value, ok := upuo.mutation.Dob(); ok {
		_spec.SetField(userprofile.FieldDob, field.TypeTime, value)
	}
	if upuo.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.LinksTable,
			Columns: []string{userprofile.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upuo.mutation.RemovedLinksIDs(); len(nodes) > 0 && !upuo.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.LinksTable,
			Columns: []string{userprofile.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upuo.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userprofile.LinksTable,
			Columns: []string{userprofile.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if upuo.mutation.EmailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.EmailsTable,
			Columns: userprofile.EmailsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upuo.mutation.RemovedEmailsIDs(); len(nodes) > 0 && !upuo.mutation.EmailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.EmailsTable,
			Columns: userprofile.EmailsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upuo.mutation.EmailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.EmailsTable,
			Columns: userprofile.EmailsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if upuo.mutation.FollowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.FollowersTable,
			Columns: userprofile.FollowersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upuo.mutation.RemovedFollowersIDs(); len(nodes) > 0 && !upuo.mutation.FollowersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.FollowersTable,
			Columns: userprofile.FollowersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upuo.mutation.FollowersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   userprofile.FollowersTable,
			Columns: userprofile.FollowersPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserProfile{config: upuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, upuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	upuo.mutation.done = true
	return _node, nil
}
