// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nibbleshift/drift/ent/user"
	"github.com/nibbleshift/drift/ent/utter"
)

// Utter is the model entity for the Utter schema.
type Utter struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Data holds the value of the "data" field.
	Data string `json:"data,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UtterQuery when eager-loading is set.
	Edges        UtterEdges `json:"edges"`
	user_utters  *int
	selectValues sql.SelectValues
}

// UtterEdges holds the relations/edges for other nodes in the graph.
type UtterEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UtterEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Utter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case utter.FieldID:
			values[i] = new(sql.NullInt64)
		case utter.FieldData:
			values[i] = new(sql.NullString)
		case utter.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case utter.ForeignKeys[0]: // user_utters
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Utter fields.
func (u *Utter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case utter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		case utter.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				u.CreatedAt = value.Time
			}
		case utter.FieldData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value.Valid {
				u.Data = value.String
			}
		case utter.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_utters", value)
			} else if value.Valid {
				u.user_utters = new(int)
				*u.user_utters = int(value.Int64)
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Utter.
// This includes values selected through modifiers, order, etc.
func (u *Utter) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Utter entity.
func (u *Utter) QueryOwner() *UserQuery {
	return NewUtterClient(u.config).QueryOwner(u)
}

// Update returns a builder for updating this Utter.
// Note that you need to call Utter.Unwrap() before calling this method if this Utter
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *Utter) Update() *UtterUpdateOne {
	return NewUtterClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the Utter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *Utter) Unwrap() *Utter {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: Utter is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *Utter) String() string {
	var builder strings.Builder
	builder.WriteString("Utter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("created_at=")
	builder.WriteString(u.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(u.Data)
	builder.WriteByte(')')
	return builder.String()
}

// Utters is a parsable slice of Utter.
type Utters []*Utter
