apiVersion: v1
kind: Service
metadata:
  name: drift-ui
  labels:
    app.kubernetes.io/name: drift-ui
    app.kubernetes.io/instance: drift
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: drift
    app.kubernetes.io/name: drift-ui
