apiVersion: v1
kind: Service
metadata:
  name: drift
  labels:
    app.kubernetes.io/name: drift-ui
    app.kubernetes.io/instance: drift
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
