version: '3'

tasks:
  default:
    cmds:
      - task: build 
  build:
    run: when_changed
    cmds:
      - yarn
    sources:
      - src/*
      - node_modules
  dev:
    run: always
    cmds:
      - yarn dev
